name: Daily Jackpot Execution

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  run-jackpot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          cd packages/hardhat
          yarn install
          
      - name: Run jackpot script
        env:
          PRIVATE_KEY: ${{ secrets.JACKPOT_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        run: |
          cd packages/hardhat
          npx ts-node scripts/interact_jackpot.ts runJackpot
          
      - name: Report status
        if: always()
        run: |
          echo "Jackpot execution completed at $(date)"
