name: Jackpot Automation

on:
  schedule:
    # Run every 5 minutes to check if jackpot can be executed
    - cron: "*/5 * * * *"
  workflow_dispatch:
    # Allow manual triggering with options
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "runJackpot"
        type: choice
        options:
          - runJackpot
          - getUserInfo
          - getJackpotInfo
          - getTicketPrice
          - getJackpotStatus
          - viewJackpotParticipants
      network:
        description: "Network to use"
        required: true
        default: "arbitrum-sepolia"
        type: choice
        options:
          - arbitrum-sepolia
          - arbitrum-one
          - ethereum

jobs:
  run-jackpot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: |
          cd packages/hardhat
          yarn install

      - name: Compile contracts
        run: |
          cd packages/hardhat
          npx hardhat compile

      - name: Run jackpot
        env:
          PRIVATE_KEY: ${{ secrets.JACKPOT_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          NETWORK: ${{ github.event.inputs.network || 'arbitrum-sepolia' }}
        run: |
          cd packages/hardhat
          npx ts-node scripts/interact_jackpot.ts ${{ github.event.inputs.action || 'runJackpot' }}

      - name: Report status
        if: always()
        run: |
          echo "Jackpot execution attempt completed at $(date)"
